### ISSUE TITLE
Runtime error on WASM

### ISSUE THREAD

**Issue by Boscop** [gluon-lang/gluon#941]
When I try to use gluon on Wasm (in a web frontend using `trunk serve`), I get this runtime error:

> Uncaught TypeError: Failed to resolve module specifier "env". Relative references must start with either "/", "./", or "../".

I'm using the latest version with these features:
```toml
gluon = { git = "https://github.com/gluon-lang/gluon", default-features = false, features = ["random"] }
gluon_codegen = { git = "https://github.com/gluon-lang/gluon" }
```
(When I don't call the function that uses gluon, the frontend works fine without errors.)

Any idea why it's not working? :)
